baseURL = 'https://bylr.info/'
defaultContentLanguage = "en"
languageCode = 'en'
title = 'bylr.info'
theme = "PaperMod"
copyright = "&copy; 2022 Antoine Beyeler –"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "G-D1H30VS7VK"
enableEmoji = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Antoine Beyeler"
description = ""
keywords = [ "Blog", "Python" ]
# author = "ab"  # don't show author
images = ["/android-chrome-512x512.png" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = true
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

[params.assets]
favicon ="/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
#safari_pinned_tab = "/safari-pinned-tab.svg"

[params.label]
text = "bylr.info"
# icon = "/apple-touch-icon.png"
# iconHeight = 35

[params.homeInfoParams]
title = "**Antoine Beyeler**"
content = "Project notes and miscellanea."


[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/abey79"

[[params.socialIcons]]
name = "github"
url = "https://github.com/abey79"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/channel/UCAuzCV4jmbqNXT-rT6U1ogw"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/abeyeler/"

[[params.socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/229511/abey"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.cover]
hidden = false
hiddenInList = false
hiddenInSingle = false

[params.editPost]
URL = "https://github.com/abey79/abey79.github.io/content"
Text = "Suggest Changes"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content" ]

[permalinks]
articles = "articles/:year/:month/:day/:slug/"

[outputs]
home = ["HTML", "RSS", "JSON"]

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "archives"
url = "/archives"
weight = 20

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 30


# This can wait to have more stuff to search
#[[menu.main]]
#identifier = "search"
#name = "search"
#url = "/search"
#weight = 30

